spring:
  datasource:
    url: jdbc:postgresql://postgres:mddbYkvIKwxllAhzAwDpnQrYybKoTAdj@viaduct.proxy.rlwy.net:28624/railway
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: createp